<?php

$this->setup(array(
    'title' => 'Delete this booking',
    'panel' => 'centered-panel',
    'back' => true
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this booking?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this booking') ?></span>
        </a>

        &nbsp;

        <a href="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['confirmed' => 'true', 'cancel' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, cancel this booking') ?></span>
        </a>

        &nbsp;

        <a href="<?= $this->url('frontend') ?>" class="default-button squarebox-close-link"><?= $this->t('No, go back') ?></a>
    </p>

    <p class="small-text gray">Wenn die Buchung storniert wird, verschwindet sie zwar vom Kalender,<br>bleibt aber in der Datenbank erhalten.</p>
</div>