<?php

$this->headScript()->appendFile($this->basePath('js/controller/backend/booking/index.search.min.js'));

if (! ($this->dateStart || $this->dateEnd)) {
    $this->dateStart = new DateTime();
    $this->dateEnd = new DateTime();
    $this->dateEnd->modify('+ 2 days');
}

?>

<div style="padding: 10px 0 16px 0;">
    <form method="get" action="<?= $this->url('backend/booking') ?>">
        <table class="default-table">
            <tr>
                <td>
                    <div class="default-form-label-top gray">
                        <label for="date-start"><?= $this->t('Date') ?>:</label>
                    </div>

                    <div class="inline-element">
                        <label for="date-start" class="inline-label symbolic symbolic-date"><span><?= $this->t('Date start') ?></span></label>
                        <input type="text" name="date-start" id="date-start" value="<?= $this->dateFormat($this->dateStart, IntlDateFormatter::MEDIUM) ?>"
                               class="inline-label-container datepicker" style="padding-left: 28px; width: 96px;">
                    </div>
                </td>

                <td style="vertical-align: bottom; padding-bottom: 7px;">
                    <?= $this->t('to') ?>
                </td>

                <td style="vertical-align: bottom;">
                    <div class="inline-element">
                        <label for="date-end" class="inline-label symbolic symbolic-date"><span><?= $this->t('Date end') ?></span></label>
                        <input type="text" name="date-end" id="date-end" value="<?= $this->dateFormat($this->dateEnd, IntlDateFormatter::MEDIUM) ?>"
                               class="inline-label-container datepicker" style="padding-left: 28px; width: 96px;">
                    </div>
                </td>

                <td>
                    <div class="default-form-label-top gray">
                        <label for="bs-filter"><?= $this->t('Filter') ?>:</label>
                    </div>

                    <input type="text" name="search" id="bs-filter" value="<?= $this->search ?>" style="width: 160px">

                    <a href="#" id="bs-filters-help" class="unlined gray">
                        <i class="symbolic symbolic-info symbol-shifted"></i>
                    </a>
                </td>

                <td style="vertical-align: bottom;">
                    <input type="submit" value="<?= $this->t('Search') ?>" class="default-button">
                </td>
            </tr>
        </table>
    </form>

    <div id="bs-filters-help-box" class="sandbox" style="display: none; margin: 26px auto 0 auto;">
        <div class="sandbox-arrow" style="right: 82px"></div>

        <p><?= $this->t('You can use filters like these to narrow your search:') ?></p>

        <?= $this->backendUserFilterHelp('User ID', '=', '1', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Square ID', '=', '1', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Status', '=', 'Single', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Status', '=', 'Subscription', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Status', '=', 'Cancelled', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing status', '=', 'Pending', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing status', '=', 'Paid', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing status', '=', 'Cancelled', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing status', '=', 'Uncollectable', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing status', '=', '[custom]', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Billing total', '>', '0', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Visibility', '=', 'Public', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Visibility', '=', 'Private', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Quantity', '>', '2', 'bs-filter-snippet') ?>
        <?= $this->backendUserFilterHelp('Created', '<', new DateTime(), 'bs-filter-snippet') ?>

        <p style="margin-top: 16px;">
            <?= $this->t('You can also combine a search term and multiple filters like this:') ?><br>
            <code>(... = ...) (... > ...)</code>
        </p>
    </div>
</div>
