<?php

$this->setup(array(
    'title' => 'Page not found',
    'panel' => 'centered-panel',
));

?>

<div class="padded centered-text">

    <h2><?= $this->t('Oops ... something went wrong here') ?></h2>
    <h1><?= $this->t('This page does not (yet) exist') ?></h1>

    <div class="separator"></div>

    <p class="gray">
        <?= sprintf($this->t('Please %sdrop us a note%s if you were expecting this page.'), '<a href="' . $this->option('client.website.contact') . '">', '</a>'); ?>
    </p>

    <div class="separator"></div>

    <a href="<?= $this->url('frontend') ?>" class="default-button"><?= $this->t('Back to front page') ?></a>

</div>