<?php

$eid = $this->event->need('eid');

$backUrl = $this->url('backend/event/edit', ['eid' => $eid]);

$this->setup(array(
    'title' => 'Delete this event',
    'panel' => 'centered-panel',
    'back' => array(
        'Event' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this event?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/event/delete', ['eid' => $eid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this event') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>
</div>