<?php

$this->setup(array(
    'title' => 'Event-Statistic',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'User-Statistic' => $this->url('backend/user/stats'),
        'Booking-Statistic' => $this->url('backend/booking/stats'),
    ),
));

$enabled = 0;

foreach ($this->stats as $stat) {
    $var = $stat['status'];
    $$var += $stat['count'];
}

$total = $enabled;

?>

<div>
    <h1><?= $this->t('Event-Statistic') ?></h1>

    <div class="separator separator-line"></div>

    <table class="bordered-table">
        <tr>
            <td><b><?= $this->t('Events') ?></b></td>
            <td class="right-text"><b><code><?= $this->numberFormat($total) ?></code></b></td>
        </tr>

        <tr>
            <td><span class="gray">&lfloor;</span> <?= $this->t('Enabled') ?></td>
            <td class="right-text">
                <code>
                    <?= $this->numberFormat($enabled) ?>
                </code>
            </td>
        </tr>
    </table>
</div>