<?php

$this->setup(array(
    'title' => 'Event-Statistic',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'User-Statistic' => $this->url('backend/user/stats'),
        'Booking-Statistic' => $this->url('backend/booking/stats'),
    ),
));

?>

<div>
    <h1><?= $this->t('Event-Statistic') ?></h1>

    <div class="separator separator-line"></div>

    <p>...</p>
</div>