<?php

$this->setup(array(
    'title' => $this->t('Edit square info and rule texts'),
    'panel' => 'centered-panel large-sized',
    'back' => array(
        $this->option('subject.square.type') . ' ' . $this->square->get('name')
            => $this->url('backend/config/square/edit', ['sid' => $this->square->need('sid')]),
    ),
));

$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.setup.light.js'));

?>

<div>
    <h1><?= $this->t('Edit square info and rule texts') ?></h1>

    <div class="separator-small"></div>

    <?= $this->backendInfo('i18n') ?>

    <div class="separator separator-line"></div>

    <div class="padded">
        <?php

        $form = $this->editForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/config/square/edit/info', ['sid' => $this->square->need('sid')]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <table class="default-table">
            <?= $this->formRowDefault($form, 'cf-info-pre') ?>
            <?= $this->formRowDefault($form, 'cf-info-post') ?>
            <?= $this->formRowDefault($form, 'cf-rules-text') ?>

            <?= $this->formRowDefault($form, 'cf-rules-document-file') ?>

            <?php if ($this->square->getMeta('rules.document.file')): ?>
                <tr>
                    <td class="default-form-label-row">&nbsp;</td>
                    <td>
                        <?= $this->t('Current file:') ?> <a href="<?= $this->basePath($this->square->getMeta('rules.document.file')) ?>" target="_blank"><?= basename($this->square->getMeta('rules.document.file')) ?></a>
                    </td>
                </tr>
            <?php endif; ?>

            <?= $this->formRowDefault($form, 'cf-rules-document-name') ?>

            <?= $this->formRowSubmit($form, 'cf-submit') ?>
        </table>

        <?= $this->form()->closeTag() ?>
    </div>
</div>