<?php

$this->setup(array(
    'title' => 'Square Groups',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Configuration' => $this->url('backend/config'),
    ),
));

?>

<div>
    <h1><?= $this->t('Court groups') ?></h1>

    <div class="separator-small"></div>

    <p><?= sprintf($this->t('Which %s-groups do you have? What are their names?'), $this->option('subject.square.type')) ?></p>

    <div class="separator separator-line"></div>

    <div class="padded">

        <?php if ($this->squareGroups): ?>
            <?= $this->backendSquareGroupsFormat($this->squareGroups) ?>
        <?php endif; ?>

        <div class="centered-text" style="margin-top: 32px;">
            <p>
                <a href="<?= $this->url('backend/config/square/squaregroup/edit') ?>" class="default-button">
                    <span class="symbolic symbolic-plus"><?= $this->t('New group') ?></span>
                </a>
            </p>
        </div>

    </div>
</div>