<?php

$backUrl = $this->url('backend/config/square/squaregroup');

$this->setup(array(
    'title' => 'Delete this group',
    'panel' => 'centered-panel',
    'back' => array(
        'Products' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this group?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/config/square/squaregroup/delete', ['sgid' => $this->sgid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this group') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>
</div>