<?php

$this->setup(array(
    'title' => 'Forgot your password?',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->passwordMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Forgot your password?') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('No need to be sad. You may simply type your email address here and you will soon be able to choose a new password.') ?>
    </p>

    <div class="separator separator-line"></div>

    <div class="padded">

        <?php

        $form = $this->passwordForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/password'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <table class="default-table">
            <tr>
                <td class="default-form-label-row">
                    <?= $this->formLabel($form->get('pf-email')) ?>
                </td>
                <td>
                    <?= $this->formElement($form->get('pf-email')) ?>
                </td>
            </tr>

            <?= $this->formRowSubmit($form, 'pf-submit') ?>
        </table>

        <?= $this->form()->closeTag() ?>

    </div>
</div>