<td class="calendar-square-col" style="width: 192px;">
    <?= $this->calendarSquareTable($this->squares, $this->timeBlockCount) ?>
</td>

<?php

$reservations = $this->get('reservations');

/* Loop through day cols */

$walkingDate = clone $this->dateStart;
$walkingIndex = 0;

while ($walkingDate <= $this->dateEnd) {
    echo sprintf('<td class="calendar-date-col %s">',
        ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 5 - $walkingIndex)) : ''));

    echo '<table class="calendar-date-table full-width">';

    echo $this->calendarDateRow($walkingDate, $this->timeBlockCount);
    echo $this->calendarTimeRow($this->timeStart, $this->timeEnd, $this->timeBlock, $this->timeBlockCount);

    /* Loop through square rows */

    foreach ($this->squares as $square) {
        echo '<tr class="calendar-core-row">';

        /* Loop through time cells */

        for ($walkingTime = $this->timeStart; $walkingTime < $this->timeEnd; $walkingTime += $this->timeBlock) {
            $walkingDate->modify('+' . $walkingTime . ' sec');

            $reservationsForColPlugin = $this->plugin('CalendarReservationsForCol');
            $reservationsForCol = $reservationsForColPlugin($reservations, $walkingDate, $walkingTime, $this->timeBlock);

            echo $this->calendarCellLogic($walkingDate, $walkingTime, $this->timeBlock, $this->dateNow, $square, $this->user, $reservationsForCol);

            $walkingDate->setTime(0, 0, 0);
        }

        echo '</tr>';
    }

    $reservationsCleanupPlugin = $this->plugin('CalendarReservationsCleanup');
    $reservationsCleanupPlugin($reservations, $walkingDate);

    echo '</table>';

    echo '</td>';

    $walkingDate->modify('+1 day');
    $walkingIndex++;
}