<td class="calendar-square-col" style="width: 192px;">
    <?= $this->calendarSquareTable($this->squares, $this->timeBlockCount) ?>
</td>

<?php

$reservations = $this->get('reservations');
$events = $this->get('events');

$reservationsForColPlugin = $this->plugin('CalendarReservationsForCol');
$reservationsCleanupPlugin = $this->plugin('CalendarReservationsCleanup');

$eventsForColPlugin = $this->plugin('CalendarEventsForCol');
$eventsCleanupPlugin = $this->plugin('CalendarEventsCleanup');

/* Loop through day cols */

$walkingDate = clone $this->dateStart;
$walkingIndex = 0;

while ($walkingDate <= $this->dateEnd) {
    if (in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptions) ||
        in_array($this->t($walkingDate->format('l')), $this->dayExceptions)) {

        if (! in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptionsExceptions)) {
            $walkingDate->modify('+1 day');
            $walkingIndex++;
            continue;
        }
    }

    echo sprintf('<td class="calendar-date-col %s">',
        ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 5 - $walkingIndex)) : ''));

    echo '<table class="calendar-date-table full-width">';

    echo $this->calendarDateRow($walkingDate, $this->timeBlockCount);
    echo $this->calendarTimeRow($this->timeStart, $this->timeEnd, $this->timeBlock, $this->timeBlockCount);

    /* Gather output: Loop through time rows */

	$output = array();

    for ($walkingTime = $this->timeStart; $walkingTime < $this->timeEnd; $walkingTime += $this->timeBlock) {
        $walkingDate->modify('+' . $walkingTime . ' sec');

        $reservationsForCol = $reservationsForColPlugin($reservations, $walkingDate, $walkingTime, $this->timeBlock);
        $eventsForCol = $eventsForColPlugin($events, $walkingDate, $walkingTime, $this->timeBlock);

        /* Gather output: Loop through square cells */

        foreach ($this->squares as $square) {
	        $sid = $square->need('sid');

            $output[$sid][$walkingTime] = $this->calendarCellLogic($walkingDate, $walkingTime,
	            $this->timeBlock, $this->dateNow, $square, $this->user, $reservationsForCol, $eventsForCol);
        }

        $walkingDate->setTime(0, 0, 0);
    }

    /* Render output: Loop through square rows */

    foreach ($this->squares as $square) {
        echo '<tr class="calendar-core-row">';

	    $sid = $square->need('sid');

        /* Render output: Loop through time cells */

        for ($walkingTime = $this->timeStart; $walkingTime < $this->timeEnd; $walkingTime += $this->timeBlock) {
            echo $output[$sid][$walkingTime];
        }

        echo '</tr>';
    }

    $reservationsCleanupPlugin($reservations, $walkingDate);
    $eventsCleanupPlugin($events, $walkingDate);

    echo '</table>';

    echo '</td>';

    $walkingDate->modify('+1 day');
    $walkingIndex++;
}
