<?php

$this->setup(array(
    'title' => $this->event->getMeta('name'),
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<div class="padded centered-text">

    <p class="large-text"><?= $this->event->getMeta('name') ?></p>

    <?= $this->squareDateFormat($this->event->needExtra('datetime_start'), $this->event->needExtra('datetime_end')) ?>

    <p>
        <?php

        if ($this->square) {
            echo sprintf('%s %s', $this->option('subject.square.type'), $this->square->need('name'));
        } else {
            echo sprintf($this->t('All %s'), $this->option('subject.square.type.plural'));
        }

        ?>
    </p>

    <div class="sandbox left-text" style="max-width: 512px;">
        <?= $this->event->getMeta('description') ?>
    </div>

</div>