<div>
    <h1>Woooaaah - you did it!</h1>

    <div class="separator-small"></div>

    <p>The initial setup is now complete and the system should basically work.</p>

    <p>All further configuration can be performed via the system backend.</p>

    <div class="separator separator-line"></div>

    <div class="sandbox">
        <div class="symbolic symbolic-warning">You should now <b>delete the file <code>/public/setup.php</code></b></div>
    </div>

    <div class="separator separator-line"></div>

    <div class="sandbox">
        <table class="default-table middle-table" style="margin: 0;">
            <tr>
                <td><img src="<?= $this->basePath('imgs/icons/topbar-face.png') ?>" alt="Thank you!"></td>
                <td>Thank you for trying our system!</td>
            </tr>
        </table>
    </div>

    <div class="separator"></div>

    <div class="centered-text">
        <a href="<?= $this->basePath('/') ?>" class="default-button">Go to your <b>fresh system</b></a>
    </div>
</div>