<?php

$backUrl = $this->url('backend/user/edit', ['uid' => $this->uid], ['query' => ['search' => $this->search]]);

$this->setup(array(
    'title' => 'Delete this user',
    'panel' => 'centered-panel',
    'back' => array(
        'User' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this user?') ?></span></p>

    <p class="no-wrap">
        <a href="<?= $this->url('backend/user/delete', ['uid' => $this->uid], ['query' => ['search' => $this->search, 'confirmed' => 'true']]) ?>" class="default-button">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this user') ?></span>
        </a>

        &nbsp;

        <a href="<?= $backUrl ?>" class="default-button"><?= $this->t('No, go back') ?></a>
    </p>

    <?php if ($this->bookings): ?>
        <p class="yellow"><?= $this->t('Since this user has already bookings, he will be set to deleted but kept in the database') ?></p>
    <?php endif; ?>
</div>