<table style="height: 100%;">
    <tr>
        <td class="responsive-pass-4" style="padding-right: 12px; border-right: solid 1px #CCC;">
            <div id="userpanel-status" class="no-wrap">
                <?= $this->t('Court types ') ?>
            </div>
        </td>
        <td>
            <select name='group-select' id='group-select'>
                <?= $this->frontendSquareGroupList() ?>
            </select>
        </td>
    </tr>
</table>

